
export interface IAddPermissionDto {
    arName: string,
    enName: string,
    isName: boolean,
    add: boolean,
    edit: boolean,
    delete: boolean,
    connectWithCompany: boolean,
    addCompaniesGroup: boolean,
    Instructions:boolean,
    copy: boolean,
    download: boolean,
    FormNotes: boolean,  
    AddFormNotes:boolean,
    Approve: boolean, 
    Complete: boolean, 
    Close: boolean, 
    Open: boolean
}
export interface IGetPermissionDto {
    id: number,
    arName: string,
    enName: string,
    isName: boolean,
    add: boolean,
    edit: boolean,
    delete: boolean,
    connectWithCompany: boolean,
    addCompaniesGroup: boolean,
    Instructions:boolean,
    copy: boolean,
    download: boolean,
    settingsAuthId: number,
    FormNotes: boolean,  
    AddFormNotes:boolean,
    Approve: boolean, 
    Complete: boolean, 
    Close: boolean, 
    Open: boolean
}